# Generated by Django 4.0.4 on 2022-05-21 13:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MBlog', '0002_postcategories_michipost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MichiStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('michi_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBlog.michiprofile')),
                ('michi_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBlog.michipost')),
            ],
        ),
    ]
