# Generated by Django 4.0.4 on 2022-05-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBlog', '0003_michistars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='michiprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='michiprofile',
            name='username',
        ),
    ]
