# Generated by Django 4.0.4 on 2022-05-22 17:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MBlog', '0004_remove_michiprofile_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='michipost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
