# Generated by Django 4.0.4 on 2022-05-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MBlog', '0005_alter_michipost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='michiprofile',
            name='eye_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='michiprofile',
            name='hair_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='michiprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
