# Generated by Django 4.0.4 on 2022-05-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MBlog', '0006_alter_michiprofile_eye_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='michipost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MBlog.postcategories'),
        ),
    ]
