# Generated by Django 4.0.4 on 2022-05-29 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MBlog', '0006_alter_michiprofile_eye_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MichiRoofs',
            fields=[
                ('roof_id', models.IntegerField(primary_key=True, serialize=False)),
                ('roof_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MichiRoofUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MChat.michiroofs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MBlog.michiprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MichiRoofChats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('michi_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MBlog.michiprofile')),
                ('roof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MChat.michiroofs')),
            ],
        ),
    ]
