# Generated by Django 4.0.4 on 2022-05-29 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MBlog', '0006_alter_michiprofile_eye_color_and_more'),
        ('MChat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='michiroofs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='michiroofs',
            name='michi_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='michi_owner', to='MBlog.michiprofile'),
            preserve_default=False,
        ),
    ]
